---
version: "2.1"
services:
  prowlarr: #Indexer
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/Los_Angeles
    volumes:
      - /apps/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  lidarr: #Music
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/Los_Angeles
    volumes:
      - /apps/docker/lidarr/config:/config
      - /mnt/v/Music:/music #optional
      - /mnt/v:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  radarr: #Movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/Los_Angeles
    volumes:
      - /apps/docker/radarr/config:/config
      - /mnt/v/Movies:/movies #optional
      - /mnt/v:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr: #eBooks/Audiobooks
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/Los_Angeles
    volumes:
      - /apps/docker/readarr/config:/config
      - /mnt/v/eBooks:/books #optional
      - /mnt/v:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  sonarr: #TVseries
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=American/Los_Angeles
    volumes:
      - /apps/docker/sonarr/config:/config
      - /mnt/v/TVseries:/tv #optional
      - /mnt/v:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped