#version: "3.1"
# Sonarr      - 8989 
# Radarr      - 7878
# Lidarr      - 8686
# Readarr     - 8787
# Readarr-ab  - 8788
# Prowlarr    - 9696
# Bazarr      - 6767
###############
services:
############### Movies ###############
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/docker/sonarr-config:/config
      - /home/docker/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
############### TV Series ###############
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    network_mode: bridge
    volumes:
      - /home/docker/docker/radarr-config:/config
      - /home/docker/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
############### Music ###############
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/docker/lidarr-config:/config
      - /home/docker/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped
############### Ebooks ###############
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/docker/readarr-config:/config
      - /home/docker/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped
############### Audiobooks ###############
#  readarr-ab:
#    image: lscr.io/linuxserver/readarr:develop
#    container_name: readarr-ab
#    environment:
#      - PUID=13007
#      - PGID=13000
#      - UMASK=002
#      - TZ=America/Los_Angeles
#    volumes:
#      - /home/docker/docker/readarr-ab-config:/config
#      - /home/docker/drive/data:/data
#    ports:
#      - 8788:8787
#    restart: unless-stopped
############### Indexer ###############
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/docker/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
############### Subtitles ###############
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - /home/docker/docker/bazarr-config:/config
      - /home/docker/data/media/movies:/movies
      - /home/docker/data/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped