#version: "3.1"
# qbittorrent - 6881/8080
# nzbget      - 6789
############### Torrent Downloader ###############
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13051 #UserID
      - PGID=13000 #GroupID
      - UMASK=002 #File permissions
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080 #WebUI Port
    volumes:
      - /home/docker/docker/qbittorrent-config:/config #qBittorrent Config
      - /home/docker/data/torrents:/data/torrents #Torrents
    ports:
      - 8080:8080 #Connect over http://localhost:8080
      - 6881:6881 #Torrent Port
      - 6881:6881/udp #Torrent Port
    restart: unless-stopped
############### Usenet Downloader ###############
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=13052 #UserID
      - PGID=13000 #GroupID
      - UMASK=002 #File permissions
      - TZ=America/Los_Angeles
      #- NZBGET_USER=nzbget #optional
      #- NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - /home/docker/docker/nzbget-config:/config #NZBGet Config
      - /home/docker/data/usenet:/data/usenet #Usenet
    ports:
      - 6789:6789 #Connect over http://localhost:6789
    restart: unless-stopped