services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - /apps/docker/overseerr/config:/config
    environment:
      - PUID=333
      - PGID=321
      - UMASK=002
    ports:
      - 5055:5055
    restart: unless-stopped
