# version: "3"
############### Automate Updates ###############
#https://containrrr.dev/watchtower/
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --run-once --cleanup
    environment:
      - WATCHTOWER_CLEANUP=TRUE #--cleanup
      #- WATCHTOWER_RUN_ONCE=TRUE #--run-once
      - WATCHTOWER_DEBUG=TRUE #--debug
      - TZ=America/Los_Angeles
      - WATCHTOWER_SCHEDULE=0 0 0 * * 0 #Run once a week at midnight between Sat/Sun