version: "3"
############### Automate Updates ###############
#https://containrrr.dev/watchtower/
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
    #host:container
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --run-once --cleanup
#    environment:
#      - WATCHTOWER_CLEANUP: 'TRUE' #--cleanup
#      - WATCHTOWER_RUN_ONCE: 'TRUE' #--run-once
#      - WATCHTOWER_DEBUG: 'TRUE' #--debug

