---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: dark #light/gray/dark
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: a_very_important_secret #will auto-generate
default_redirection_url: https://auth.local.krpros.org
totp: #time based one-time-password
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

#This can be updated to use like an AD setup instead of the file
authentication_backend:
  file:
    path: /config/users_database.yaml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control: #applies to all the routs
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.krpros.org #public website
      policy: bypass
    - domain: heimdall.local.example.com
      policy: one_factor
    - domain: pve1.local.example.com
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: krpros.org  # Should match whatever your root protected domain is

#needed only for HA mode
  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

#Stop brute force attacks
regulation:
  max_retries: 3 #failed attempts
  find_time: 120 #over a set time
  ban_time: 300 #ban time

storage:
  encryption_key: a_very_important_secret # Now required
  local:
    path: /config/db.sqlite3

#setup a way for users to reset their passwords
#mailgun, free service
notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /config/notification.txt