global:
#  checkNewVersion: true
  sendAnonymousUsage: false #sending anonymous usage to the developers

api:
  dashboard: true #Allow dashboard

log:
  level: INFO # INFO | DEBUG | ERROR

serversTransport:
  insecureSkipVerify: true #allows a self signed to be behind Traefik

entryPoints:
  http:
    address: :80
    forwardedHeaders:
      trustedIPs:
        # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections: #force redirect to https
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    forwardedHeaders:
      trustedIPs:
        # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
      http:
        tls:
          # Generate a wildcard domain certificate
          certResolver: letsencrypt
          domains:
            - main: krpros.org
              sans:
                - '*.krpros.org'
        middlewares:
          - securityHeaders@file
          - auth@file

providers:
  providersThrottleDuration: 2s
  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /config.yaml  #references the config in the same folder
    watch: true
  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: proxy #network used by Traefik
    # Default host rule to containername.domain.example
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.krpros.org`)"
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
    endpoint: "tcp://dockersocket:2375" # Uncomment if you are using docker socket prox
    #endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  cloudflare: #point to 'cloudflare' or 'letsencrypt'
    acme: #Certificate storage
      email: tkonsonlas26@outlook.com #cloudflare email
      storage: acme.json #file certificates will be stored in
      dnsChallenge:
        provider: cloudflare #point to dns provider
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers: #Have to point to cloudflare resolvers
          - "1.1.1.1:53"
          - "1.0.0.1:53"